require("dotenv").config();
const nodemailer = require("nodemailer");

const {
  EMAIL_USER,
  EMAIL_PASS,
  SMTP_HOST,
  SMTP_PORT,
} = process.env;

async function sendTestEmail() {
  console.log("📧 Setting up SMTP transporter...");
  console.log(`   Host : ${SMTP_HOST}`);
  console.log(`   Port : ${SMTP_PORT}`);
  console.log(`   User : ${EMAIL_USER?.trim()}`);

  const transporter = nodemailer.createTransport({
    host: SMTP_HOST,
    port: Number(SMTP_PORT),
    secure: Number(SMTP_PORT) === 465, // true for port 465 (SSL)
    auth: {
      user: EMAIL_USER?.trim(),
      pass: EMAIL_PASS?.trim(),
    },
  });

  // Verify connection before sending
  console.log("\n🔌 Verifying SMTP connection...");
  await transporter.verify();
  console.log("✅ SMTP connection verified successfully!\n");

  const mailOptions = {
    from: `"NDSICDE Platform" <${EMAIL_USER?.trim()}>`,
    to: "neutrondavis@gmail.com",
    subject: "✅ Test Email – NDSICDE Backend SMTP Check",
    text: "This is a plain-text test email sent from the NDSICDE backend using Nodemailer.",
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e0e0e0; border-radius: 8px;">
        <h2 style="color: #2d6a4f;">✅ SMTP Test Successful</h2>
        <p style="color: #333; font-size: 15px;">
          This is a <strong>test email</strong> sent from the <strong>NDSICDE Mearl Platform</strong> backend to verify SMTP credentials and connectivity.
        </p>
        <hr style="border: none; border-top: 1px solid #e0e0e0; margin: 20px 0;" />
        <table style="width: 100%; font-size: 14px; color: #555;">
          <tr>
            <td style="padding: 4px 0;"><strong>SMTP Host:</strong></td>
            <td>${SMTP_HOST}</td>
          </tr>
          <tr>
            <td style="padding: 4px 0;"><strong>SMTP Port:</strong></td>
            <td>${SMTP_PORT}</td>
          </tr>
          <tr>
            <td style="padding: 4px 0;"><strong>Sender:</strong></td>
            <td>${EMAIL_USER?.trim()}</td>
          </tr>
          <tr>
            <td style="padding: 4px 0;"><strong>Recipient:</strong></td>
            <td>neutrondavis@gmail.com</td>
          </tr>
          <tr>
            <td style="padding: 4px 0;"><strong>Timestamp:</strong></td>
            <td>${new Date().toUTCString()}</td>
          </tr>
        </table>
        <hr style="border: none; border-top: 1px solid #e0e0e0; margin: 20px 0;" />
        <p style="color: #888; font-size: 12px;">
          This email was auto-generated by the NDSICDE backend test script. No action is required.
        </p>
      </div>
    `,
  };

  console.log("📤 Sending test email to neutrondavis@gmail.com ...");
  const info = await transporter.sendMail(mailOptions);

  console.log("🎉 Email sent successfully!");
  console.log(`   Message ID : ${info.messageId}`);
  console.log(`   Response   : ${info.response}`);
}

sendTestEmail().catch((err) => {
  console.error("❌ Failed to send email:");
  console.error(err.message);
  process.exit(1);
});
